# Generated by Django 5.1.2 on 2024-10-27 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchshop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
    ]
