# Generated by Django 5.1.2 on 2024-10-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
