# Generated by Django 5.1.2 on 2024-10-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchshop_app', '0002_remove_watchlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
