# Generated by Django 5.1.2 on 2024-10-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchshop_app', '0002_alter_watch_brand_remove_watch_category_delete_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='name',
        ),
    ]
