# Generated by Django 5.1.2 on 2024-10-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchshop_app', '0003_remove_watch_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watch',
            new_name='Watchs',
        ),
    ]
