# Generated by Django 5.1.2 on 2024-10-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchshop_app', '0003_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
