# Generated by Django 5.1.2 on 2024-10-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchshop_app', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True),
        ),
    ]
