# Generated by Django 5.1.2 on 2024-10-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchshop_app', '0004_rename_watch_watchs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watchs',
            new_name='Watch',
        ),
    ]
