# Generated by Django 5.1.2 on 2024-10-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchshop_app', '0006_rename_watch_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watches', models.ManyToManyField(related_name='wishlists', to='watchshop_app.watchlist')),
            ],
        ),
    ]
